"""Auto-generated by select_attention_model.py; do not edit manually."""

SELECTED_MODEL_KEY = 'LiteDARE-L2'
SELECTED_MODEL_NAME = 'LiteDARE-L2'
SELECTED_ENCODER_LAYERS = 2
SELECTED_CHECKPOINT = '/root/lite dare/DARE/lite_dare/runs/DiscreteLiteDARE_NodeEncSA_L2_H4_D256_DecL1_H4/seed_42_20260730_095849/checkpoints/epoch=0150-val_loss=0.058.ckpt'
RANDOM_SEED = 42
DELTA_FINAL_COVERAGE = 0.01
DELTA_SUCCESS_RATE = 0.02
DELTA_COVERAGE_AUC = 0.02
SELECTION_TIE_TOLERANCE = 0.05
SIMILARITY_DISTANCE_TO_L6 = 0.256669132015357
PERFORMANCE_PRESERVED = True
SELECTION_REASON = 'LiteDARE variant with the smallest normalised exploration distance to DARE-L6 using paired success-rate, final-coverage and Coverage-AUC differences; model cost is excluded from the distance, and L2 is preferred only for an effective tie.'
